# ...

- name: Print Docker Version
  run: |
    docker --version
    docker buildx version

- name: Build and push Docker image
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  run: |
    echo "DEBUG: Current directory is $(pwd)"
    docker buildx create --use
    docker buildx inspect --bootstrap
    docker buildx build --platform linux/amd64,linux/arm64 -t your-docker-username/flask-docker-demo:latest .
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker push your-docker-username/flask-docker-demo:latest
